// <auto-generated />
using System;
using EmployeeAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714073530_seedlog")]
    partial class seedlog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAPI.Models.AllowedIP", b =>
                {
                    b.Property<Guid>("AllowedIPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllowedIPId");

                    b.HasIndex("CompanyId");

                    b.ToTable("AllowedIPs");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerDay")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.Property<Guid>("DutyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DutyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DutyDetailId");

                    b.HasIndex("DutyId");

                    b.HasIndex("UserId");

                    b.ToTable("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("EmployeeAPI.Models.LogStatusConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryMultiplier")
                        .HasColumnType("float");

                    b.Property<int>("enumId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("LogStatusConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a356d277-d902-4ee4-abea-209475628832"),
                            IsSystemDefault = true,
                            Name = "None",
                            Note = "Chưa checkin/checkout",
                            SalaryMultiplier = 0.0,
                            enumId = 0
                        },
                        new
                        {
                            Id = new Guid("74d5dd05-15f0-47cc-847f-f9daa1f05b0f"),
                            IsSystemDefault = true,
                            Name = "OnTime",
                            Note = "Đi đúng giờ",
                            SalaryMultiplier = 1.0,
                            enumId = 1
                        },
                        new
                        {
                            Id = new Guid("08eafcc1-dc50-4c78-8cbe-7d07a760b3b7"),
                            IsSystemDefault = true,
                            Name = "Late",
                            Note = "Đi trễ",
                            SalaryMultiplier = 0.69999999999999996,
                            enumId = 2
                        },
                        new
                        {
                            Id = new Guid("da365ea0-63d5-43c1-9041-9ca1035c2e0c"),
                            IsSystemDefault = true,
                            Name = "LeaveEarly",
                            Note = "Về sớm",
                            SalaryMultiplier = 0.69999999999999996,
                            enumId = 3
                        },
                        new
                        {
                            Id = new Guid("8b08faba-35d3-4951-9db9-10bbcac4cfea"),
                            IsSystemDefault = true,
                            Name = "LateAndLeaveEarly",
                            Note = "Đi trễ và về sớm",
                            SalaryMultiplier = 0.5,
                            enumId = 4
                        },
                        new
                        {
                            Id = new Guid("871473b1-5528-4870-be86-fa2b8afbad79"),
                            IsSystemDefault = true,
                            Name = "Overtime",
                            Note = "Làm thêm giờ",
                            SalaryMultiplier = 1.3,
                            enumId = 5
                        },
                        new
                        {
                            Id = new Guid("7b0d6f5a-ac95-45e2-b38d-7c3a51c6ab98"),
                            IsSystemDefault = true,
                            Name = "LateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ",
                            SalaryMultiplier = 0.69999999999999996,
                            enumId = 6
                        },
                        new
                        {
                            Id = new Guid("0c705b2a-9d65-4f53-9899-600b679459f6"),
                            IsSystemDefault = true,
                            Name = "Absent",
                            Note = "Vắng",
                            SalaryMultiplier = 0.0,
                            enumId = 7
                        },
                        new
                        {
                            Id = new Guid("ce6a7402-d9a1-416e-a0de-06b3738d0e70"),
                            IsSystemDefault = true,
                            Name = "OnHoliday",
                            Note = "Làm vào ngày nghỉ",
                            SalaryMultiplier = 2.0,
                            enumId = 8
                        },
                        new
                        {
                            Id = new Guid("a92a985a-d572-4e0c-aaf2-82d088d53deb"),
                            IsSystemDefault = true,
                            Name = "OnHolidayLate",
                            Note = "Đi trễ vào ngày nghỉ",
                            SalaryMultiplier = 1.5,
                            enumId = 9
                        },
                        new
                        {
                            Id = new Guid("f1be3ddd-e335-408c-bd70-c06586140130"),
                            IsSystemDefault = true,
                            Name = "OnHolidayLeaveEarly",
                            Note = "Về sớm vào ngày nghỉ",
                            SalaryMultiplier = 1.5,
                            enumId = 10
                        },
                        new
                        {
                            Id = new Guid("d4389218-f965-4803-a87a-d3c9cbf3ba8c"),
                            IsSystemDefault = true,
                            Name = "OnHolidayOvertime",
                            Note = "Làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 3.0,
                            enumId = 11
                        },
                        new
                        {
                            Id = new Guid("149c3474-8834-416a-a025-b4239a5146a3"),
                            IsSystemDefault = true,
                            Name = "OnHolidayLateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 1.5,
                            enumId = 12
                        },
                        new
                        {
                            Id = new Guid("b450d4b9-e3d1-4463-ba19-a715fbcc700b"),
                            IsSystemDefault = true,
                            Name = "OnHolidayLateAndLeaveEarly",
                            Note = "Đi trễ và về sớm vào ngày nghỉ",
                            SalaryMultiplier = 2.0,
                            enumId = 13
                        },
                        new
                        {
                            Id = new Guid("b71749b1-0575-42cb-9016-3394d2e9844f"),
                            IsSystemDefault = false,
                            Name = "Others",
                            Note = "Khác",
                            SalaryMultiplier = 0.5,
                            enumId = 14
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("EmployeeAPI.Models.ScheduleTime", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("EndTimeMorning")
                        .HasColumnType("time");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("bit");

                    b.Property<int>("LogAllowtime")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTimeMorning")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ScheduleTimes");

                    b.HasData(
                        new
                        {
                            id = new Guid("bf10b6e0-aefa-4e6e-989a-a2fc7ec12890"),
                            EndTimeAfternoon = new TimeOnly(17, 0, 0),
                            EndTimeMorning = new TimeOnly(12, 0, 0),
                            IsSystemDefault = true,
                            LogAllowtime = 5,
                            StartTimeAfternoon = new TimeOnly(13, 0, 0),
                            StartTimeMorning = new TimeOnly(8, 0, 0)
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerHour")
                        .HasColumnType("float");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("isResetPass")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.AllowedIP", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", null)
                        .WithMany("AssignedDuties")
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedBy");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Duty", "Duty")
                        .WithMany("DutyDetails")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("DutyDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Holiday", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.LogStatusConfig", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Payrolls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeAPI.Models.ScheduleTime", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmployeeAPI.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Navigation("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Navigation("AssignedDuties");

                    b.Navigation("Checkins");

                    b.Navigation("DutyDetails");

                    b.Navigation("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
