// <auto-generated />
using System;
using EmployeeAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711085721_seed-data")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAPI.Models.AllowedIP", b =>
                {
                    b.Property<Guid>("AllowedIPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllowedIPId");

                    b.ToTable("AllowedIPs");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerDay")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80c0ef36-6e5e-4317-a7ca-72a15f65d787"),
                            CompanyId = new Guid("1ff65895-a518-45be-970f-3a8d3ac7ef7b"),
                            Name = "Phòng nhân sự",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("308dcc3a-cd28-45c6-a0c3-7e0c8431c741"),
                            CompanyId = new Guid("1ff65895-a518-45be-970f-3a8d3ac7ef7b"),
                            Name = "Phòng Kế toán",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("09b8da2b-31b3-4898-bfe5-36bbfbd3960d"),
                            CompanyId = new Guid("8d562f29-88db-4a55-868c-d792afac1b35"),
                            Name = "Phòng Kinh doanh",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("2e6edaa5-94d7-4107-8539-66b9aa23b929"),
                            CompanyId = new Guid("1ff65895-a518-45be-970f-3a8d3ac7ef7b"),
                            Name = "Phòng Kỹ thuật",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ea8bc86c-afe5-4b62-aed5-f366ef02c25d"),
                            CompanyId = new Guid("8d562f29-88db-4a55-868c-d792afac1b35"),
                            Name = "Phòng Marketing",
                            isDeleted = false
                        },
                        new
                        {
                            Id = new Guid("69df13da-3a35-40ec-9a36-b4936de78faf"),
                            CompanyId = new Guid("e4a2c07d-a149-410c-8217-f0a695a400f8"),
                            Name = "Phòng Chăm sóc Khách hàng",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.Property<Guid>("DutyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DutyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DutyDetailId");

                    b.HasIndex("DutyId");

                    b.HasIndex("UserId");

                    b.ToTable("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("EmployeeAPI.Models.LogStatusConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryMultiplier")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("LogStatusConfigs");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Note = "Chưa checkin/checkout",
                            SalaryMultiplier = 0.0
                        },
                        new
                        {
                            Id = 1,
                            Name = "OnTime",
                            Note = "Đi đúng giờ",
                            SalaryMultiplier = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Late",
                            Note = "Đi trễ",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Name = "LeaveEarly",
                            Note = "Về sớm",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Name = "LateAndLeaveEarly",
                            Note = "Đi trễ và về sớm",
                            SalaryMultiplier = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Name = "Overtime",
                            Note = "Làm thêm giờ",
                            SalaryMultiplier = 1.3
                        },
                        new
                        {
                            Id = 6,
                            Name = "LateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 7,
                            Name = "Absent",
                            Note = "Vắng",
                            SalaryMultiplier = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "OnHoliday",
                            Note = "Làm vào ngày nghỉ",
                            SalaryMultiplier = 2.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "OnHolidayLate",
                            Note = "Đi trễ vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 10,
                            Name = "OnHolidayLeaveEarly",
                            Note = "Về sớm vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 11,
                            Name = "OnHolidayOvertime",
                            Note = "Làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 3.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "OnHolidayLateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 13,
                            Name = "OnHolidayLateAndLeaveEarly",
                            Note = "Đi trễ và về sớm vào ngày nghỉ",
                            SalaryMultiplier = 2.0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Others",
                            Note = "Khác",
                            SalaryMultiplier = 0.5
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isPaied")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f78de4d3-cc57-4c67-a2bb-cad4ac1680a5"),
                            IsDeleted = false,
                            Name = "Trưởng phòng"
                        },
                        new
                        {
                            Id = new Guid("b214e44c-f4df-4da6-ba7c-d6fbf74a9d7b"),
                            IsDeleted = false,
                            Name = "Phó phòng"
                        },
                        new
                        {
                            Id = new Guid("535e00bc-c78b-4eea-a947-6d54a3487772"),
                            IsDeleted = false,
                            Name = "Nhân viên Kinh doanh"
                        },
                        new
                        {
                            Id = new Guid("d76dd682-b9ea-4249-bac8-88d984ba6a5d"),
                            IsDeleted = false,
                            Name = "Nhân viên Kế toán"
                        },
                        new
                        {
                            Id = new Guid("4a9d2395-f07c-4709-9d16-399950b67a5c"),
                            IsDeleted = false,
                            Name = "Nhân viên Nhân sự"
                        },
                        new
                        {
                            Id = new Guid("6d80a752-40e3-475e-94c4-2cf5f3509d82"),
                            IsDeleted = false,
                            Name = "Nhân viên IT"
                        },
                        new
                        {
                            Id = new Guid("2a741f5e-810c-48b8-96f1-15e6b658a43e"),
                            IsDeleted = false,
                            Name = "Chuyên viên Marketing"
                        },
                        new
                        {
                            Id = new Guid("4a62cd3d-152f-4e38-9e0d-26a8efe2d4f6"),
                            IsDeleted = false,
                            Name = "Nhân viên Chăm sóc Khách hàng"
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.ScheduleTime", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("EndTimeMorning")
                        .HasColumnType("time");

                    b.Property<int>("LogAllowtime")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTimeMorning")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("ScheduleTimes");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerHour")
                        .HasColumnType("float");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("8ac8b469-86bd-4f52-8e4d-570d108caddc"),
                            Address = "TP. HCM",
                            Fullname = "Phạm Đức Cường",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "/Ej0pz2A2vAPDMvjF0m+XDCZlaOnzCpTVrfof+xdUwDjAvc0",
                            PhoneNumber = "0901000011",
                            RefreshToken = "",
                            Role = 0,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "AdminSystem123"
                        },
                        new
                        {
                            UserId = new Guid("3f547245-97dc-4f5b-a04e-5f37c948e719"),
                            Address = "TP. HCM",
                            Fullname = "Phạm Đức Cường",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "cdXrdDW4w6I3kuOM65Q/my+xy30cquBEuXG3RtaQRNeAMhQ5",
                            PhoneNumber = "0901000012",
                            RefreshToken = "",
                            Role = 1,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Admin01"
                        },
                        new
                        {
                            UserId = new Guid("c26d1d56-5e1d-427c-bb28-c43d0993a95a"),
                            Address = "TP. HCM",
                            Fullname = "Phạm Đức Cường",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "6i5ed7aFsmujkrlKoD7PQIlZUX6VtIrIE2X9B9tiQ1PFHJAy",
                            PhoneNumber = "0901000013",
                            RefreshToken = "",
                            Role = 1,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Admin02"
                        },
                        new
                        {
                            UserId = new Guid("3d9f7131-3859-41e4-8435-ee7de27fa66c"),
                            Address = "Hà Nội",
                            Fullname = "Nguyễn Văn Quang",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "edr5n0qkSOCr9NdazKMQTRm3FYZDdbi8ndf/bkaCqd5UbV5Z",
                            PhoneNumber = "0901000001",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Manager01"
                        },
                        new
                        {
                            UserId = new Guid("321d99d1-2739-4650-8e53-7bd9ebb672ba"),
                            Address = "TP. HCM",
                            Fullname = "Lê Thị Hoa",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "datOQMBTe2eVa6xWe2NbZbOungvAelOhp5M622sSluq8XgvV",
                            PhoneNumber = "0901000002",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Manager02"
                        },
                        new
                        {
                            UserId = new Guid("4767bee1-c828-44e8-92a0-3ad4a807c11f"),
                            Address = "Hà Nội",
                            Fullname = "Nguyễn Phúc Hậu",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "jL7f9dVhVAIExuCBPy10lQAwWDQVa/Q1fEney62FXkQyYQNk",
                            PhoneNumber = "0901000009",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 18000.0,
                            TokenVersion = 0,
                            Username = "Manager03"
                        },
                        new
                        {
                            UserId = new Guid("59223633-ba87-4751-a96d-177eac4bc57b"),
                            Address = "Hà Nội",
                            Fullname = "Lê Bảo Nhân",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "kiJp2n1Ttcy8rPOCGrrZum0M3ujgGEojKd+qtsjmU0r1A3PO",
                            PhoneNumber = "0901000010",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 15000.0,
                            TokenVersion = 0,
                            Username = "Manager04"
                        },
                        new
                        {
                            UserId = new Guid("6b1627ad-e9cb-47f2-963f-7c267caa97eb"),
                            Address = "Ninh Bình",
                            Fullname = "Trần Minh Quân",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "AlTGljwB6Ff256OxfGUcm3nGtemZXvmULpv550b2l0tQOaCz",
                            PhoneNumber = "0901000008",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 10000.0,
                            TokenVersion = 0,
                            Username = "User01"
                        },
                        new
                        {
                            UserId = new Guid("5d87b1c8-cc35-4ffc-abf2-c5ba3150e9b9"),
                            Address = "Hải Phòng",
                            Fullname = "Phạm Văn An",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "rG18iitZDTtiINPBs0TFvgimaB8egWMW3XGIgVqLXsYeAqsS",
                            PhoneNumber = "0901000003",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 12000.0,
                            TokenVersion = 0,
                            Username = "User02"
                        },
                        new
                        {
                            UserId = new Guid("81a76852-c1d1-4ac8-ad74-fb433b24101c"),
                            Address = "Đà Nẵng",
                            Fullname = "Nguyễn Phúc Bảo",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "csh/K3ESNwMpX6rqHLnyMCnnrxVjgZEEZ4ZwexGF70q4RRUI",
                            PhoneNumber = "0901000004",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 15000.0,
                            TokenVersion = 0,
                            Username = "User03"
                        },
                        new
                        {
                            UserId = new Guid("ebdc3f05-7300-4092-80fe-5eb5247e9d67"),
                            Address = "Huế",
                            Fullname = "Trần Minh Đức",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "hX++/NrLW/BrmDrSBx3mt0yfjC9iFgzCAS713qYIB9l/zu9m",
                            PhoneNumber = "0901000005",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 8000.0,
                            TokenVersion = 0,
                            Username = "User04"
                        },
                        new
                        {
                            UserId = new Guid("400b2826-5497-4c15-a657-65db3e02a852"),
                            Address = "Cần Thơ",
                            Fullname = "Lê Văn Dũng",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "aabxZ5nblBOakM+lp9GAmlD7kQKLu8ld94qDuimcLlCjj2RP",
                            PhoneNumber = "0901000006",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 5000.0,
                            TokenVersion = 0,
                            Username = "User05"
                        },
                        new
                        {
                            UserId = new Guid("687dd9c9-a82c-4aa4-8629-7decdf69bb85"),
                            Address = "Bình Dương",
                            Fullname = "Vũ Thị Ngọc Bích",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "KQU+0pC291P1oHVZkUgyFO5cP09l7XjbMay4ttqnmIp0iPWN",
                            PhoneNumber = "0901000007",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 12000.0,
                            TokenVersion = 0,
                            Username = "User06"
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", null)
                        .WithMany("AssignedDuties")
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedBy");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Duty", "Duty")
                        .WithMany("DutyDetails")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("DutyDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Payrolls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmployeeAPI.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Navigation("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Navigation("AssignedDuties");

                    b.Navigation("Checkins");

                    b.Navigation("DutyDetails");

                    b.Navigation("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
