// <auto-generated />
using System;
using EmployeeAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711082934_them-user")]
    partial class themuser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeAPI.Models.AllowedIP", b =>
                {
                    b.Property<Guid>("AllowedIPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllowedIPId");

                    b.ToTable("AllowedIPs");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckoutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LogStatus")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerDay")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.ToTable("Duties");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.Property<Guid>("DutyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DutyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DutyDetailId");

                    b.HasIndex("DutyId");

                    b.HasIndex("UserId");

                    b.ToTable("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("EmployeeAPI.Models.LogStatusConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalaryMultiplier")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("LogStatusConfigs");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "None",
                            Note = "Chưa checkin/checkout",
                            SalaryMultiplier = 0.0
                        },
                        new
                        {
                            Id = 1,
                            Name = "OnTime",
                            Note = "Đi đúng giờ",
                            SalaryMultiplier = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Late",
                            Note = "Đi trễ",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Name = "LeaveEarly",
                            Note = "Về sớm",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Name = "LateAndLeaveEarly",
                            Note = "Đi trễ và về sớm",
                            SalaryMultiplier = 0.5
                        },
                        new
                        {
                            Id = 5,
                            Name = "Overtime",
                            Note = "Làm thêm giờ",
                            SalaryMultiplier = 1.3
                        },
                        new
                        {
                            Id = 6,
                            Name = "LateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ",
                            SalaryMultiplier = 0.69999999999999996
                        },
                        new
                        {
                            Id = 7,
                            Name = "Absent",
                            Note = "Vắng",
                            SalaryMultiplier = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "OnHoliday",
                            Note = "Làm vào ngày nghỉ",
                            SalaryMultiplier = 2.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "OnHolidayLate",
                            Note = "Đi trễ vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 10,
                            Name = "OnHolidayLeaveEarly",
                            Note = "Về sớm vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 11,
                            Name = "OnHolidayOvertime",
                            Note = "Làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 3.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "OnHolidayLateAndOvertime",
                            Note = "Đi trễ và làm thêm giờ vào ngày nghỉ",
                            SalaryMultiplier = 1.5
                        },
                        new
                        {
                            Id = 13,
                            Name = "OnHolidayLateAndLeaveEarly",
                            Note = "Đi trễ và về sớm vào ngày nghỉ",
                            SalaryMultiplier = 2.0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Others",
                            Note = "Khác",
                            SalaryMultiplier = 0.5
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysWorked")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isPaied")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("EmployeeAPI.Models.ScheduleTime", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("EndTimeMorning")
                        .HasColumnType("time");

                    b.Property<int>("LogAllowtime")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTimeAfternoon")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTimeMorning")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("ScheduleTimes");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("SalaryPerHour")
                        .HasColumnType("float");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("4bb4af3b-d172-4108-a7d3-73257cbea84c"),
                            Address = "Hà Nội",
                            Fullname = "Nguyễn Văn Quang",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "DiMXpjS7sJ+r9qrrIpnly64KZ8QZqtMqs9G/8grgq2AxAk0e",
                            PhoneNumber = "0901000001",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Manager01"
                        },
                        new
                        {
                            UserId = new Guid("ce8b19d6-fbd2-4781-b0a0-a2fce49c6b37"),
                            Address = "TP. HCM",
                            Fullname = "Lê Thị Hoa",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "sHDbOMkHJWoH5kd8w2w4c6d7+E0ozPuCwmk1O40L1zJjkvl6",
                            PhoneNumber = "0901000002",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 20000.0,
                            TokenVersion = 0,
                            Username = "Manager02"
                        },
                        new
                        {
                            UserId = new Guid("7b021be6-c477-4dd4-89dd-67e7916a7b0d"),
                            Address = "Hà Nội",
                            Fullname = "Nguyễn Phúc Hậu",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "v0UtYeysX9i7BubBElkarwDzXtmC3wmnUKIssAXtZmpAA9B1",
                            PhoneNumber = "0901000009",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 18000.0,
                            TokenVersion = 0,
                            Username = "Manager03"
                        },
                        new
                        {
                            UserId = new Guid("641771ad-dde6-437d-9c4a-38cf7064630a"),
                            Address = "Hà Nội",
                            Fullname = "Lê Bảo Nhân",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "Jl6AjwMfoXtLqTWVDpNGHvK8AhLQK/GUcnxay7Ovh2m8JNTG",
                            PhoneNumber = "0901000010",
                            RefreshToken = "",
                            Role = 2,
                            SalaryPerHour = 15000.0,
                            TokenVersion = 0,
                            Username = "Manager04"
                        },
                        new
                        {
                            UserId = new Guid("846692d4-d919-4b49-915e-7724824c35de"),
                            Address = "Ninh Bình",
                            Fullname = "Trần Minh Quân",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "HxfTkSNfSkBfVQVn9B013R7tbD8Sk8SVd/+Wt9jpXtec3SC5",
                            PhoneNumber = "0901000008",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 10000.0,
                            TokenVersion = 0,
                            Username = "User01"
                        },
                        new
                        {
                            UserId = new Guid("4baf844c-b009-4dc7-b41b-d40bd6516bc0"),
                            Address = "Hải Phòng",
                            Fullname = "Phạm Văn An",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "E0Yn2qgiHJw2k6tok1y9Krg3x0U96QDG7L6MN6JsYBrfu3K4",
                            PhoneNumber = "0901000003",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 12000.0,
                            TokenVersion = 0,
                            Username = "Employee02"
                        },
                        new
                        {
                            UserId = new Guid("152738ba-4a3f-4fc4-ac33-b39a8cbe71a6"),
                            Address = "Đà Nẵng",
                            Fullname = "Nguyễn Phúc Bảo",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "tHQAWj+qap6c3KwjGXhVowUhogBYjGpZFYZbrEnFqgZWFA4d",
                            PhoneNumber = "0901000004",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 15000.0,
                            TokenVersion = 0,
                            Username = "Employee03"
                        },
                        new
                        {
                            UserId = new Guid("5967e51c-4a4e-4d4b-b9ac-603a5c0dcdf4"),
                            Address = "Huế",
                            Fullname = "Trần Minh Đức",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "TH14IuYAmLEpz8z9HTg70lAnDChwvwVTgqri+d6U/tYcpin1",
                            PhoneNumber = "0901000005",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 8000.0,
                            TokenVersion = 0,
                            Username = "Employee04"
                        },
                        new
                        {
                            UserId = new Guid("e72839f3-209b-4449-a240-e69b7abe8d52"),
                            Address = "Cần Thơ",
                            Fullname = "Lê Văn Dũng",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "sH4PFnyOU2Om9xBEvgD0jhC69v9n2gN3Vbtei+C4orm/L64e",
                            PhoneNumber = "0901000006",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 5000.0,
                            TokenVersion = 0,
                            Username = "Employee05"
                        },
                        new
                        {
                            UserId = new Guid("d4f2a1bd-8a24-456a-a8a3-c1bb03f2fa78"),
                            Address = "Bình Dương",
                            Fullname = "Vũ Thị Ngọc Bích",
                            ImageUrl = "",
                            IsActive = true,
                            IsDeleted = false,
                            Password = "ircMRUaJ5uGQpUsdz0x42Mk6BVnUd+GpHK+taIlQHBAa7gLr",
                            PhoneNumber = "0901000007",
                            RefreshToken = "",
                            Role = 3,
                            SalaryPerHour = 12000.0,
                            TokenVersion = 0,
                            Username = "Employee06"
                        });
                });

            modelBuilder.Entity("EmployeeAPI.Models.Checkin", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", null)
                        .WithMany("AssignedDuties")
                        .HasForeignKey("UserId");

                    b.Navigation("AssignedBy");
                });

            modelBuilder.Entity("EmployeeAPI.Models.DutyDetail", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Duty", "Duty")
                        .WithMany("DutyDetails")
                        .HasForeignKey("DutyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("DutyDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Payroll", b =>
                {
                    b.HasOne("EmployeeAPI.Models.User", "Users")
                        .WithMany("Payrolls")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.HasOne("EmployeeAPI.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("EmployeeAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmployeeAPI.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Department", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Duty", b =>
                {
                    b.Navigation("DutyDetails");
                });

            modelBuilder.Entity("EmployeeAPI.Models.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EmployeeAPI.Models.User", b =>
                {
                    b.Navigation("AssignedDuties");

                    b.Navigation("Checkins");

                    b.Navigation("DutyDetails");

                    b.Navigation("Payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
